CREATE OR REPLACE FUNCTION doping(rider STRING)
  RETURN IF(current_user()!='demo_databricks_user@posit.co', true, rider NOT IN (
    -- This list was generated by asking Claude for a list of known doping cyclists
    "Armstrong Lance",
    "Landis Floyd",
    "Hamilton Tyler",
    "Ullrich Jan",
    "Pantani Marco",
    "Contador Alberto",
    "Valverde Alejandro",
    "Vinokourov Alexandre",
    "Basso Ivan",
    "Rasmussen Michael",
    "Schleck Frank",
    "Kreuziger Roman",
    "Rebellin Davide",
    "Di Luca Danilo",
    "Ricco Riccardo",
    "Petacchi Alessandro",
    "Scarponi Michele",
    "Sanchez Samuel",
    "Cobo Juan Jose",
    "Horner Chris",
    "Mosquera Ezequiel",
    "Piepoli Leonardo",
    "Kohl Bernhard",
    "Sella Emanuele",
    "Jaksche Jorg",
    "Zabel Erik",
    "Millar David",
    "Boonen Tom",
    "Dekker Thomas",
    "Rabon Dane",
    "Devolder Stijn"
  ));
    
ALTER TABLE stages SET ROW FILTER doping ON (rider);